<!-- kg:begin -->
kg (Project Knowledge Growth) — managed block, rendered from `knowledge/`. Do not edit by hand.

- HARD RULE: never read `.kg/` during a work task — it holds uncompiled claims and pipeline state. Writes go only through the kg-observe skill; reads happen only inside kg-compile sessions.
- Record observations (task end, or IMMEDIATELY on human correction): `.agents/skills/kg-observe/SKILL.md`.
- Compile pending observations into knowledge: `.agents/skills/kg-compile/SKILL.md`.
- Bootstrap an existing codebase into evidence-backed document drafts: `.agents/skills/kg-scan/SKILL.md`.
- Draft and revise complete ADRs, RFCs, and technical plans directly under `docs/`; follow `docs/README.md`. KG does not gate document authoring.

Active project knowledge (read the entry before working in its scope):

- KN-0001 [project_knowledge] KYAML inline maps cannot contain lists; schema field specs encode enums as one pipe-separated string. → `knowledge/KN-0001-kyaml-inline-maps-cannot-contain-lists.md`
- KN-0002 [project_knowledge] Record scripts validate the RAW input first (rejecting unknown fields), then rebuild in canonical field order before writing; kyaml.stringify preserves insertion order. → `knowledge/KN-0002-build-records-in-canonical-field-order.md`
- KN-0003 [project_contract] Skill scripts must reach shared code only via the _lib.mjs resolver, and every install mode — checkout, --copy, and registry (npx skills add) — must preserve the lib/../../protocol layout; registry installers copy ONLY the skill directory, so scripts/lib/ and protocol/ are committed vendored inside every skills/<name>/ and scripts/sync-vendored.mjs (--check) guards drift. → `knowledge/KN-0003-skill-scripts-must-reach-shared-code.md`
- KN-0004 [project_contract] A host repo's installed kg layout is .agents/skills/kg-* self-contained copies only; the root checkout layout (skills/ protocol/ scripts/) belongs exclusively to the plugin source repo. → `knowledge/KN-0004-a-host-repo-s-installed-kg.md`
- KN-0005 [project_knowledge] Destructive refresh (rm-then-copy) must first prove src and dest differ by canonical identity — fs.realpathSync with a resolve fallback for not-yet-existing paths; vendored re-runs and symlink aliases both collapse src==dest. → `knowledge/KN-0005-destructive-refresh-rm-then-copy-must.md`
- KN-0006 [project_knowledge] npx skills add owner/repo distributes the repo's DEFAULT branch only; unmerged branch fixes never reach consumers, and branch URLs whose branch name contains a slash fail the CLI's parsing — test unmerged branches from a local clone. → `knowledge/KN-0006-npx-skills-add-owner-repo-distributes.md`
- KN-0007 [project_knowledge] Node ESM resolves import.meta.url through symlinks, so argv[1]-vs-import.meta.url main-module checks must realpath argv[1] first — otherwise symlink-installed scripts silently skip their CLI entrypoint (exit 0, no output). → `knowledge/KN-0007-node-esm-resolves-import-meta-url.md`
- KN-0008 [project_knowledge] Claude Code reads CLAUDE.md (never AGENTS.md) and discovers skills under .claude/skills/; kg-init wires both — .claude/skills/kg-* symlinks to the canonical .agents/skills/ copies plus an @AGENTS.md import in CLAUDE.md — but only when the host shows Claude markers (.claude/ dir or CLAUDE.md). → `knowledge/KN-0008-claude-code-reads-claude-md-never.md`
- KN-0009 [project_contract] Knowledge entries stay atomic — one claim per entry; fragmentation is treated at the render layer, and merge is reserved for true duplication or supersession, never topical aggregation. → `knowledge/KN-0009-knowledge-entries-stay-atomic-one-claim.md`
- KN-0010 [project_contract] kg is two layers with different stability commitments: the ledger layer (schemas, authority ranking, lifecycle, queue, evidence/regret chain) is the product and must stay stable; the render layer (folding, sinking, budgets, three-source assembly) is a platform-generation adapter expected to be replaced wholesale, whose patches count as normal wear, not debt. → `knowledge/KN-0010-kg-is-two-layers-with-different.md`
- KN-0011 [project_knowledge] Karpathy's llm-wiki (gist, 2026) is the closest prior art to kg's compiler mental model; kg differs on input stream (work-process signals vs external documents), consumption (publish-as-injection vs query), record unit (atomic claim with evidence/authority vs topic page), trust model (governed untrusted compiler vs trusted librarian), and knowledge endpoint (prose graduates into machine constraints vs stays prose). → `knowledge/KN-0011-karpathy-s-llm-wiki-gist-2026.md`
- KN-0012 [project_knowledge] kg rendered surfaces and knowledge entries should prefer pointer-form constraints (file paths, commands, entry links) over descriptive prose: pointer constraints fail loudly like a 404 when they rot, prose constraints rot silently — design for rot. → `knowledge/KN-0012-kg-rendered-surfaces-and-knowledge-entries.md`
- KN-0013 [project_knowledge] The always-loaded AGENTS.md managed block must stay a compact pointer index with detail lazy-loaded from knowledge/ entries, because model instruction compliance degrades as the always-on instruction count grows — this is the external rationale behind the render-layer line budget and its do-not-raise-the-budget rule. → `knowledge/KN-0013-the-always-loaded-agents-md-managed.md`
- KN-0014 [project_contract] KG must allow humans and agents to directly draft and iterate complete ADR, RFC, and MVP design documents; the observation pipeline may learn from those artifacts but must not gate their creation. → `knowledge/KN-0014-kg-must-allow-humans-and-agents.md`
- KN-0015 [project_contract] kg-init Setup resolves project stage (greenfield or brownfield) and document profile (none, lean, or standard), creates only missing template files, and routes brownfield hosts to a separate kg-scan session. → `knowledge/KN-0015-kg-init-setup-resolves-project-stage.md`
- KN-0016 [project_contract] kg-scan is the brownfield bootstrap adapter: it is static-only by default, excludes .kg, secrets, and symlinks, executes no host code without explicit authorization, and produces drafts or patch proposals without silent overwrite. → `knowledge/KN-0016-kg-scan-is-the-brownfield-bootstrap.md`
- KN-0017 [project_contract] kg-compile consumes only registered project documents with status accepted; ordinary Markdown and draft, proposed, rejected, or superseded registered documents remain outside compilation. → `knowledge/KN-0017-kg-compile-consumes-only-registered-project.md`
- KN-0018 [project_knowledge] kg-init must compute relative skill symlink targets from canonicalized source and parent paths so filesystem aliases such as /var and /private/var cannot create broken links. → `knowledge/KN-0018-kg-init-must-compute-relative-skill.md`
<!-- kg:end -->
